graph LR
  Start --> howtoread[How to Read a Candlestick Chart] 
	howtoread --> onebar(1-Bar)
		onebar-->Hammer
		onebar-->HangingMan
		onebar-->Doji
	howtoread	--> twobar(2-bar)
		
click howtoread "https://www.dailyfx.com/education/candlestick-patterns/how-to-read-candlestick-charts.html"
